-- Seed data for Funds
insert into public.funds (name_en, name_ar, manager_en, logo, return_1y, return_ytd, category, risk_level, description_en, strategy_en, min_investment, fees, status)
values
(
  'CIB Wealth Fund', 
  'صندوق CIB للثروة', 
  'CIB', 
  'https://upload.wikimedia.org/wikipedia/en/thumb/d/d1/Commercial_International_Bank_Logo.svg/1200px-Commercial_International_Bank_Logo.svg.png',
  26.5, 
  18.2, 
  'Equity', 
  'High', 
  'A premier equity fund targeting long-term capital appreciation through a diversified portfolio of high-growth Egyptian companies.', 
  'Invests primarily in top 50 EGX companies with strong fundamentals.', 
  5000, 
  1.5, 
  'active'
),
(
  'Azimut Egypt Equity Fund', 
  'صندوق أزيموت مصر للأسهم', 
  'Azimut', 
  'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Azimut_Holding_logo.svg/2560px-Azimut_Holding_logo.svg.png',
  25.8, 
  17.9, 
  'Equity', 
  'High', 
  'Focuses on achieving superior returns by investing in a mix of blue-chip and growth stocks in the Egyptian market.', 
  'Active management with a focus on sector rotation and stock selection.', 
  10000, 
  1.8, 
  'active'
),
(
  'EFG Hermes One', 
  'صندوق هيرميس وان', 
  'EFG Hermes', 
  'https://mubasher.mncdn.com/GK_News_En_2016/21/02/2016/10520161210021052016121002_1.jpg',
  24.1, 
  16.5, 
  'Equity', 
  'High', 
  'Designed for aggressive growth, this fund leverages EFG Hermes deep market insights to identify high-potential opportunities.', 
  'High-conviction equity portfolio.', 
  2500, 
  2.0, 
  'active'
),
(
  'Allianz Life Assurance', 
  'أليانز لتأمينات الحياة', 
  'Allianz', 
  'https://upload.wikimedia.org/wikipedia/commons/thumb/6/63/Allianz_logo.svg/2048px-Allianz_logo.svg.png',
  21.8, 
  14.1, 
  'Mixed', 
  'Medium', 
  'A balanced fund offering a mix of capital appreciation and income generation through equities and fixed income instruments.', 
  '60% Equities, 40% Fixed Income.', 
  1000, 
  1.2, 
  'active'
),
(
  'Faisal Islamic Bank Fund', 
  'صندوق بنك فيصل الإسلامي', 
  'Faisal Bank', 
  'https://upload.wikimedia.org/wikipedia/ar/7/7c/Faisal_Islamic_Bank_of_Egypt_logo.png',
  19.2, 
  13.5, 
  'Islamic', 
  'Medium', 
  'Provides competitive returns while strictly adhering to Sharia principles, investing in compliant sectors.', 
  'Sharia-compliant equities and sukuk.', 
  5000, 
  1.0, 
  'active'
),
(
  'Ahli United Alpha Fund', 
  'صندوق ألفا البنك الأهلي المتحد', 
  'Ahli United', 
  'https://upload.wikimedia.org/wikipedia/en/thumb/8/8e/Ahli_United_Bank_Logo.svg/1200px-Ahli_United_Bank_Logo.svg.png',
  18.5, 
  12.8, 
  'Equity', 
  'High', 
  'Seeks to outperform the benchmark by investing in a concentrated portfolio of market leaders.', 
  'Alpha generation through active stock picking.', 
  10000, 
  1.75, 
  'active'
),
(
  'QNB Al Ahli Fund', 
  'صندوق بنك قطر الوطني الأهلي', 
  'QNB', 
  'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/QNB_Group_Logo.svg/2560px-QNB_Group_Logo.svg.png',
  17.9, 
  11.5, 
  'Equity', 
  'High', 
  'A diversified equity fund aiming for long-term growth with a focus on financial and industrial sectors.', 
  'Diversified equity exposure.', 
  1000, 
  1.5, 
  'active'
),
(
  'Thndr Growth Fund', 
  'صندوق ثندر للنمو', 
  'Thndr', 
  'https://thndr.app/wp-content/uploads/2021/01/Thndr-Logo-01.png',
  17.5, 
  11.2, 
  'Tech', 
  'High', 
  'Invests in technology and innovation-driven companies to capture the growth of the digital economy.', 
  'Tech and innovation focused.', 
  500, 
  1.0, 
  'active'
),
(
  'NBE Fund 1', 
  'صندوق البنك الأهلي المصري الأول', 
  'NBE', 
  'https://upload.wikimedia.org/wikipedia/en/thumb/a/a2/National_Bank_of_Egypt_Logo.svg/1200px-National_Bank_of_Egypt_Logo.svg.png',
  16.8, 
  10.9, 
  'Fixed Income', 
  'Low', 
  'A low-risk fund designed to preserve capital and provide regular income through government securities.', 
  'Treasury bills and government bonds.', 
  5000, 
  0.5, 
  'active'
),
(
  'Banque Misr Fund II', 
  'صندوق بنك مصر الثاني', 
  'Banque Misr', 
  'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Banque_Misr_Logo.svg/1200px-Banque_Misr_Logo.svg.png',
  16.2, 
  10.5, 
  'Growth', 
  'Medium', 
  'Balances growth and stability by investing in a mix of equities and fixed income instruments.', 
  'Balanced growth strategy.', 
  2000, 
  1.25, 
  'active'
),
(
  'Credit Agricole Fund 1', 
  'صندوق كريدي أجريكول الأول', 
  'Credit Agricole', 
  'https://upload.wikimedia.org/wikipedia/en/thumb/6/6f/Credit_Agricole_Logo.svg/1200px-Credit_Agricole_Logo.svg.png',
  15.9, 
  10.2, 
  'Balanced', 
  'Medium', 
  'Aims to provide moderate capital growth with lower volatility than pure equity funds.', 
  '50% Equity, 50% Fixed Income.', 
  5000, 
  1.3, 
  'active'
),
(
  'Alex Bank Fund 1', 
  'صندوق بنك الإسكندرية الأول', 
  'Alex Bank', 
  'https://upload.wikimedia.org/wikipedia/en/thumb/6/68/Bank_of_Alexandria_Logo.svg/1200px-Bank_of_Alexandria_Logo.svg.png',
  15.5, 
  9.8, 
  'Money Market', 
  'Low', 
  'Ideal for short-term liquidity management, offering stable returns with very low risk.', 
  'Short-term money market instruments.', 
  1000, 
  0.4, 
  'active'
),
(
  'NBK Ishraq Liquidity', 
  'صندوق إشراق للسيولة', 
  'NBK', 
  'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6c/NBK_Logo.svg/1200px-NBK_Logo.svg.png',
  14.8, 
  9.5, 
  'Islamic', 
  'Low', 
  'A Sharia-compliant liquidity fund offering competitive returns for short-term savings.', 
  'Islamic money market instruments.', 
  5000, 
  0.6, 
  'active'
),
(
  'SAIB Fund 2', 
  'صندوق بنك الشركة المصرفية العربية الدولية الثاني', 
  'SAIB', 
  'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Saib_Bank_Logo.svg/1200px-Saib_Bank_Logo.svg.png',
  14.2, 
  9.1, 
  'Fixed Income', 
  'Low', 
  'Focuses on income generation through a diversified portfolio of corporate and government bonds.', 
  'Fixed income securities.', 
  10000, 
  0.7, 
  'active'
),
(
  'FABMisr Modkharaty', 
  'صندوق مدخراتي', 
  'FABMisr', 
  'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/First_Abu_Dhabi_Bank_logo.svg/1200px-First_Abu_Dhabi_Bank_logo.svg.png',
  13.9, 
  8.8, 
  'Money Market', 
  'Low', 
  'A secure place for your savings with daily liquidity and attractive returns.', 
  'Daily liquidity money market.', 
  500, 
  0.3, 
  'active'
);
